### ISSUE TITLE
remove QA - Topo Visit Validation schema from cm.org

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#104]
unless this is a testing schema...

**Comment by MattReimer** [comment]
Nope. I thought we wanted it. Originally this was where the automation was going to consume its triggers (back in the time when we thought full automation was a thing)

I'll remove it.  @KellyMWhitehead do you have any opinions on it?

**Comment by KellyMWhitehead** [comment]
I don't fully understand the implications, but am fine either way.

**Comment by MattReimer** [comment]
@KellyMWhitehead  There are no implications on my end. I just want to make sure you don't need those validation schemas for anything.

I will do two things:

1. Delete the metric schema
2. Stop the automation from creating it next time we run.

From now on you will need to get your validation status from the XML files on S3

**Comment by MattReimer** [comment]
talked to Carol. Let's leave it. We're going to have a discussion about QA process later.
