### ISSUE TITLE
Aux Visit Metrics: Pool Tail Fines LT6 and LT2 missing

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#110]
Visit 4798 has missing pool tail fines metrics even though data exists.  I suspect this is because ALL Grid 3 values are null.  These nulls need to be ignored and the calculation should continue with Grid 1 and 2 data.

![2017-11-08_105110](https://user-images.githubusercontent.com/13526689/32568338-c56ca2ec-c472-11e7-8712-2674c5363866.png)

**Comment by MattReimer** [comment]
@volkcj OK, this one is really gnarly. It affects some really 

Here's the code affected by this: 

https://github.com/SouthForkResearch/CHaMP_Metrics/blob/master/tools/auxmetrics/metriclib/reachMetrics.py#L303-L383

I'm up for sorting this out if you are but we're going to have to be really careful.

**Comment by MattReimer** [comment]
Ok. I think I've got a solution. @volkcj can you double check these numbers for `VISIT_4798` before I commit anything?

``` xml			<PercentOfObservationsLessThan2mm>1.17647058824</PercentOfObservationsLessThan2mm>			<PercentOfObservationsLessThan6mm>1.52941176471</PercentOfObservationsLessThan6mm>
```

**Comment by volkcj** [comment]
good to go.  confirmed with a manual calc for visit 4798.
