### ISSUE TITLE
Visit schema LWCount is null when wood count is 0. (AUX)

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#111]
See #109.  I believe we fixed this for the channel unit schema, but not for the visit schema.  Example visit is 4876.  There is no wood and it should be 0, not null.

**Comment by MattReimer** [comment]
We decided that Tier1 and Channel metrics for `<LargeWoodyPiecesCount>` should be zeroes and not null.
