### ISSUE TITLE
UcutArea should be 0s not Nulls in 2017 (topo aux)

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#113]
Older datasets (e.g. visits 1215 and 1218) show 0s for this metric but newer datasets show nulls not zeros.

**Comment by MattReimer** [comment]
from the logs:
```
[error] [MissingException] 404 Error: https://api.champmonitoring.org/api/v1/visits/5111/measurements/Undercut Banks
[info] [methods.undercut] Running UndercutMetrics
[error] [MissingException] UndercutBanks missing from apiData
```

**Comment by volkcj** [comment]
5111 has no undercut area for the visit at all.  We need to gracefully  handle no values for this code.  'if there's no value for the undercut area returned from the api', then make the value be 0'.
