### ISSUE TITLE
Topo Aux metric LWDFreq_Bf not validating

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#115]
Dry LWD Count is 14 and Wet LWD Count is 3 and wetted site length is 129.  

LWDFreq_Bf should be ~ 17/129, which is 13.17.  Current metric is 4.63
Visit 116 example visit

**Comment by MattReimer** [comment]
Could be related to #116

**Comment by MattReimer** [comment]
I'm calling this fixed. 

```xml
					<Bankfull>13.1310228912</Bankfull>
					<Wetted>2.31723933375</Wetted>
```
