### ISSUE TITLE
metric: thalweg crosses channel unit

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#17]
Thalweg exit depths are currently null if thalweg doesn't pass through channel unit.  This is valid, but there's no way to xcheck that thalweg exit depths are null because of this reason.  Suggest we add a 1/0 or y/n attribute to each channel unit to indicate whether the thalweg passes through the channel unit.

**Comment by philipbaileynar** [comment]
This has been implemented as part of the solution for tier 1 and tier 2 residual depth (issue #36). There is now a channel unit level metric called `ThlawegIntersect` that is `1` (True) when the Thalweg intersects a channel unit, or `0` (zero, False) when it does not.

```
<Item>
	<Tier1>Slow/Pool</Tier1>
	<Volume>0.0</Volume>
	<Tier2>Scour Pool</Tier2>
	<ChannelUnitNumber>3</ChannelUnitNumber>
	<Area>15392.7192913</Area>
	<DepthAtThalwegExit>0.601135253906</DepthAtThalwegExit>
	<ThalwegIntersect>1</ThalwegIntersect>
	<Length>354.710763809</Length>
	<MaxDepth>2.41479492188</MaxDepth>
	<ResidualDepth>-1.81365966797</ResidualDepth>
</Item>
```
