### ISSUE TITLE
Raster "min" property reflecting NoData Value

### ISSUE THREAD

**Issue by KellyMWhitehead** [SouthForkResearch/CHaMP_Metrics#18]
I came across this Raster that is reporting the NoData value as the min. This is the first (and only?) raster I have come across where this has happened. 

![image](https://cloud.githubusercontent.com/assets/10746997/24518103/87527ed8-1535-11e7-8281-f20b855a904e.png)

[DEM.zip](https://github.com/SouthForkResearch/CHaMP_Metrics/files/883299/DEM.zip)

**Comment by MattReimer** [comment]
Ok. This is good to know. There's a little weirdness with floating point numbers we need to sort out.

**Comment by MattReimer** [comment]
## The Problem

The problem is that the nodata value is set as a fundamentally different value than the values that are in the array. Take a look:


```python
from decimal import *

nodata = -3.40282e+38
themin = -3.402823e+38

nodataD = Decimal(nodata)
theminD = Decimal(themin)


print "nodata: {}".format(nodataD)
print "min:    {}".format(theminD)
```

    nodata: -340282000000000014192072600942972764160
    min:    -340282299999999994960115009090224128000


So what I suggest is that, instead of using the `self.nodata` value, we check first if the array's minimum is close to it and use that instead


```python
                workingNodata = self.nodata
                self.min = np.nanmin(self.array)
                if isclose(self.min, self.nodata, rel_tol=1e-03):
                    workingNodata = self.min
