### ISSUE TITLE
Missing metric in python results: "Wetted Channel Mainstem Sinuosity"

### ISSUE THREAD

**Issue by MattReimer** [SouthForkResearch/CHaMP_Metrics#20]
from my metric definition (exported as CSV from access)

```xml
<Metric name="Wetted Channel Mainstem Sinuosity" xpath="Wetted/Centerline/Mainstem/Sinuosity" type="numeric"/>
```
from the python results:

```xml
<?xml version="1.0" ?>
<TopoMetrics>
	...
	<Metrics>
		...
		<Wetted>
			<Centerline>
				<ChannelCount>2</ChannelCount>
				<SideChannelCount>1</SideChannelCount>
				<MainstemLength>247.571868525</MainstemLength>
				<TotalChannelLength>276.974470042</TotalChannelLength>
				<SideChannelLength>29.4026015166</SideChannelLength>
				<MainstemSinuosity>1.22757886296</MainstemSinuosity>
				<MainstemCount>1</MainstemCount>
				<ChannelType>complex</ChannelType>
				<AverageSideChannelLength>138.487235021</AverageSideChannelLength>
				<Braidedness>1.11876390356</Braidedness>
			</Centerline>
		</Wetted>
	</Metrics>
</TopoMetrics>
```

Notice that this object from the xml isn't as deep as the xpath

**Comment by philipbaileynar** [comment]
The correct XPath in the topo metric XML result file is:

```
/TopoMetrics/Metrics/Wetted/Centerline/MainstemSinuosity
```

This has been updated in the CHaMP Workbench and also in the metric XML definition file and the change pushed up on `dev` branch. Ticket reassigned to @MattReimer for integration onto `master` branch.

**Comment by MattReimer** [comment]
This has been updated in the automation so it should be picked up now

https://github.com/Riverscapes/CHaMPAutomation/blob/e2dac9064d9de606d079d9349034a0857a938587/templates/XML/TopoVisitMetrics.xml#L14
