### ISSUE TITLE
Bankfull and Wetted Main Channel Width Avg, CV, SD all zeros

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#25]
Topo Metrics 1.0.0 reporting all zeros in Metric Validation report.   This isn't an active metric, so this might be an xml path issue and not a calculation issue.  Suggest checking Metric_Definitions and comparing to Bankfull Channel Width Avg.

**Comment by philipbaileynar** [comment]
This was missing XPaths. See issue #31 this should now be resolved.
