### ISSUE TITLE
Detrended Elevation SD does not validate

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#26]
Very few validations against manual and 6.0.4 values.  
Review Visits 2007, 995, and 228 for examples of non-validating Visits.
Visits 606, 1142 and 310 do validate.
v.1.0.0. always higher than manual or 6.0.4 values

**Comment by philipbaileynar** [comment]
## IMPORTANT!

See issue #16 for very probably cause of this issue!

**Comment by philipbaileynar** [comment]
Topo Metric Validation Report on root of NARDrive called `2017_05_17_TopoMetricValidation.htm`

**Comment by MattReimer** [comment]
This required a change to the automation so we can download `Detrended.tif`

It also required a schema change

https://github.com/Riverscapes/CHaMPAutomation/commit/4230e3d0f2dcfcc0653141bb23ee4d89bdf0b346
