### ISSUE TITLE
Update IsActive status

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#28]
Update IsActive status to 1 in Workbench db. List attached
[UpdateIsActiveList_20170508.txt](https://github.com/SouthForkResearch/CHaMP_Metrics/files/984640/UpdateIsActiveList_20170508.txt)

**Comment by philipbaileynar** [comment]
This was implemented on Philip's Master Workbench database on 17 May 2017. I incremented the workbench database version to 41 as part of this change.

Note: The SQL used only changed the specified metrics to `IsActive = 1`. I didn't change any other values to zero first etc.

```
UPDATE Metric_Definitions SET IsActive = 1 where MetricID IN (19,20,22,23,40,45,68,71,75,78,80,82,90,92,137,139,143,145,149,151,155,157,161,163,167,169,3269,3271,3275,3277,3281,3283,3287,3289,3293,3295,3299,3301,3357,3358,3359,3360,3374,3375,3376)
```
