### ISSUE TITLE
Bankfull Channel Qualifying Island Area does not validate

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#29]
suspect non-qualifying island areas are included.  e.g. visit ids 1525, 606 have 0 qualifying island area but v 1.0.0 has 15.27 m2.

**Comment by philipbaileynar** [comment]
I've downloaded the latest Harold data for visit 1525 and verified that the Python code is reporting the correct values for the GIS data. See the following image. Is there a possibility that the GIS data have changed over time?

![2017-05-17_123420](https://cloud.githubusercontent.com/assets/8645379/26172413/2dae0594-3afd-11e7-8b0b-b4ba11e8dd88.png)

**Comment by philipbaileynar** [comment]
Related to issue #30

**Comment by volkcj** [comment]
Metric doesn't validate with 5/19 version of SQL db sent to CV.  The Topo Metric code is reading off of `Qualifying` attribute to indicate whether an island is qualifying.  Code should use` IsValid` attribute instead.

**Comment by philipbaileynar** [comment]
I can confirm that the metric code should be using the `IsValid` attribute. I just generated an island feature class and used the Toolbar to switch the status of an island polygon. Sure enough the toolbar user interface was setting the `IsValid` field.

![2017-05-24_140106](https://cloud.githubusercontent.com/assets/8645379/26425438/9a9832f6-4089-11e7-95c1-7a2043d1ea35.png)

**Comment by philipbaileynar** [comment]
See commit 72cc14b90e3b89e2485eabc9b3e1e535954c23f4
