### ISSUE TITLE
bankfull channel qualifying island count doesn't validate

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#30]
check visit 320, 2648 as good examples of not validating.

**Comment by philipbaileynar** [comment]
Related to issue #29

**Comment by philipbaileynar** [comment]
Downloaded latest Harold results for visit 2648. Verified that there are 4 qualifying islands and that this is also the value being produced by the Python code.

![2017-05-17_124937](https://cloud.githubusercontent.com/assets/8645379/26173094/77d1d6a8-3aff-11e7-9c07-fe53b5c190bf.png)

**Comment by volkcj** [comment]
see issue #29  Use `IsValid` to indicate Qualifying Islands instead of `Qualifying`

**Comment by philipbaileynar** [comment]
See issue #29 for resolution.
