### ISSUE TITLE
MetricID 3377 (Polygon Area) missing Xpath in Metric_Definitions

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#36]
CHANNEL UNITS (TypeID=6):
Metric ID 3377 (Polygon Area)

TIER 2 (TypeID=5)
MetricID 3369 (Thalweg Max Depth Avg)
MetricID 3370 (Thalweg Exit Depth Avg)
MetricID 3371 (Residual Depth)
MetricID 3378 (Tier 2 Polygon area)

TIER 1 (TypeID=4)
MetricID 3365 (Thalweg max depth--might also be known as channel unit max depth at tier1)
MetricID 3366 (Thalweg Exit Depth)
MetricID 3367 (Residual Depth)

VISIT (TypeID=3)
MetricID 9 (Slow Water Area)
MetricID 10 (Slow Water Count)
MetricID 11 (Slow Water Spacing)
MetricID 12 (Slow Water Volume)
MetricID 13 (Slow Water Percent)
MetricID 14 (Fast Turbulent Area)
MetricID 15 (Fast TUrbulent Count)
MetricID 16 (Fast Turbulent SPacing)
MetricID 17 (Fast Turbulent Volume)
MetricID 18 (Fast Turublent Percent)
MetricID 19 (Fast NonTurbulent Area)
MetricID 20 (FastNonTurbulent Count)
MetricID 21 (Fast NonTurbulent Spacing)
MetricID 23 (Fast Turbulent PErcent)

After these are all done, do the following filter to make sure all the xpaths are populated.
Filter by:  TypeID=3 and ModelID = 15 and IsDisplayable = 1

as reviewed in 5/11 'for carol' sql db.  These are visible metrics on cm.org

**Comment by philipbaileynar** [comment]
These are all done except the following:

* Tier 1
    * MetricID 3367 (Residual Depth)
* Tier 2
    * MetricID 3371 (Residual Depth)

**Comment by philipbaileynar** [comment]
See related issue  #31
