### ISSUE TITLE
Tier1, Tier2, Channel Unit metrics to import

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#37]
[ValidationMetrics_Tier1_2_ChannelUnits_SQLFormat_20170511.xlsx](https://github.com/SouthForkResearch/CHaMP_Metrics/files/994592/ValidationMetrics_Tier1_2_ChannelUnits_SQLFormat_20170511.xlsx)

**Comment by philipbaileynar** [comment]
This was imported into the Workbench database on 11th May 2017
