### ISSUE TITLE
Bankfull and Wetted Depth Metrics Missing

### ISSUE THREAD

**Issue by philipbaileynar** [SouthForkResearch/CHaMP_Metrics#39]
The validation report is missing both wetted and bankfull depth metrics despite values appearing in the result XML.

`SELECT MetricID, Title, XPath FROM Metric_Definitions WHERE Title like '%Wetted Depth%' or title like 'Bankfull Depth%'`

Original text for bankfull:

The Python code is not calculating and reporting `Bankfull Depth CV` (Metric ID 4643). This should probably be reviewed for the correct method of calculation. The most likely method would be to use NumPy and report it along with the other water extent metrics `Mean` and `Max`.

```
<Bankfull>
    <WaterExtent>
        <Volume>2240.3190625</Volume>
        <IntegratedWidth>22.1639696006</IntegratedWidth>
        <Depth>
             <Max>0.582824707031</Max>
             <Mean>0.253076767642</Mean>
        </Depth>
        <Area>13368.4087065</Area>
    </WaterExtent>
</Bankfull>
```

**Comment by volkcj** [comment]
add both of these to visit metric schema

**Comment by philipbaileynar** [comment]
This is actually a missing metric calculation, not a validation report / metric schema problem.

**Comment by volkcj** [comment]
Resolved in 5/31 version of wb database from 5/31 scraping of validation metrics
