### ISSUE TITLE
Channel Unit Tier Metrics Missing From Validation Report

### ISSUE THREAD

**Issue by philipbaileynar** [SouthForkResearch/CHaMP_Metrics#42]
The visit level channel unit metrics are missing from the validation report. It's weird the values look good in the XML result files! The **visit level** metrics affected are:

```
Slow Water Area
Slow Water Count
Slow Water Spacing
Slow Water Volume
Slow Water Percent
Fast Turbulent Area
Fast Turbulent Count
Fast Turbulent Spacing
Fast Turbulent Volume
Fast Turbulent Percent
Fast NonTurbulent Area
Fast NonTurbulent Count
Fast NonTurbulent Spacing
Fast NonTurbulent Volume
Fast NonTurbulent Percent
Slow Water Frequency
Fast Turbulent Frequency
Fast NonTurbulent Frequency
Residual Pool Depth
```

`SELECT MetricID, Title, XPath FROM Metric_Definitions WHERE XPath like '%ChannelUnitsTier%' AND TypeID = 3`

**Comment by philipbaileynar** [comment]
This is because all these metrics are missing form the [CHaMP Automation Metric Schema Definition](Fast NonTurbulent Count)

**Comment by volkcj** [comment]
add the areas, volumes, percents, frequencies, and residual pool depth to the metric schemas.  Skip spacing.

**Comment by philipbaileynar** [comment]
I've set `IsActive = 1` in the Workbench for all but the *spacing* metrics listed above. 

When @MattReimer  is back in the office we can use the new Workbench schema XML generator to export an updated XML schema file for visit level metrics. i.e. these metrics are still missing from the visit level schema XML file.

**Comment by philipbaileynar** [comment]
The [visit level metric definition XML](https://github.com/Riverscapes/CHaMPAutomation/blob/master/templates/XML/TopoVisitMetrics.xml) has been updated and should reflect these metrics next time the metrics are scraped.
