### ISSUE TITLE
Thalweg Depth Avg Missing from Topo Metrics

### ISSUE THREAD

**Issue by philipbaileynar** [SouthForkResearch/CHaMP_Metrics#44]
`Thalweg Depth Avg` (Metric ID 3360) is missing from the validation report. What's weird is that other Thalweg based metrics are present in the report:

`SELECT MetricID, Title, XPath FROM Metric_Definitions WHERE Title like '%Thalweg Depth%'`

**Comment by philipbaileynar** [comment]
This is caused by the metric not appearing in [CHaMP Automation metric schema definition](https://github.com/Riverscapes/CHaMPAutomation/blob/master/templates/XML/TopoVisitMetrics.xml)

**Comment by volkcj** [comment]
please add this to the visit metric schema.

**Comment by philipbaileynar** [comment]
Added to CHaMP Automation metric schema on 18 May 2017.

**Comment by philipbaileynar** [comment]
Verified that Thalweg Depth Mean is in both the [visit level Metric Definition XML](https://github.com/Riverscapes/CHaMPAutomation/blob/master/templates/XML/TopoVisitMetrics.xml) and also the workbench. Should scrape on next run.
