### ISSUE TITLE
Validation Issues Required for Topo Metrics

### ISSUE THREAD

**Issue by philipbaileynar** [SouthForkResearch/CHaMP_Metrics#45]
Topo Metrics was run for all ~ 1,700 historical visits for which we have Harold results. Approximately 600 visits failed due to what are flagged as *data exceptions*. These are data issues that prevent Topo Metrics from being calculated. Note that Topo Metrics exits upon first experiencing a data exception and so there might be additional data problems shadowed by these exception. The [600 data exceptions are available here](https://gist.github.com/MattReimer/8694fab5cd026e94a172ad20195d5900) and can be summarized into small number of categories:

* Missing water depth raster (347 occurrences)
* Missing bankfull centerline (224)
* Field called `Channel` missing from wetted centerline (26)
* Channel units in GIS that are not in aux (6)
* Multipart centerline (3)
* Missing wetted centerline (2)
* `Null` value in `Channel` field in wetted centerline (1)
* Strange donuts in water extent (1)
* Thalweg appears to be a polygon not a polyline geometry (1)
* Thalweg in flow point is not on raster (1)

The first, obvious, thing to note is that all these issues should be verified as validation checks in Kelly's Validation Python script. We are not going to change the topo metrics handling or logging for these issues. It is the responsibility of the validation script to detect these issues, log them and report error. This will prevent the Topo Metrics from running.

The one topic for discussion is whether visits with missing water depth rasters should be allowed to calculate metrics **if and only if their DEM raster and Water Surface DEM raster are both present and concurrent**. This would avoid the need to fix hundreds of topo visits.

**Comment by philipbaileynar** [comment]
Summary from various discussions on this topic:

* Keep topo metrics as dumb and simple as possible. Do **not** implement workaround for missing water depth rasters in topo metrics.
* Validation script will detect and log missing water depth rasters.
* The ArcPy script that converts old survey GDBs to Topo Project format will take responsibility for creating missing water depth rasters (if the DEM and WSDEM are concurrent).

**Comment by volkcj** [comment]
Log file reviewed from Validation Run.  Log record exists for all validation checks listed in this issue (as of 7/19/17).
