### ISSUE TITLE
missing gradient metric

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#50]
Gradient is missing from the TM1.0.0 validation dataset sent on 5/19.

**Comment by philipbaileynar** [comment]
Gradient is now the "percentage" value (i.e. out of 100 and not a ratio out of 1). It is defined this way in the [visit level Metric Definition XML file](https://github.com/Riverscapes/CHaMPAutomation/blob/master/templates/XML/TopoVisitMetrics.xml). It's active in the Workbench with a valid XPath. Should work in next scrape.
