### ISSUE TITLE
missing Residual Pool Depth from Visit level metrics

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#51]
This might not be a bug--please comment.  Is RPD only being exposed at channel unit/tier 1/tier 2 levels now?

**Comment by philipbaileynar** [comment]
Residual Pool Depth does exist in Workbench (Metric ID 3372). It was missing from [Metric Definition XML file](https://github.com/Riverscapes/CHaMPAutomation/blob/master/templates/XML/TopoVisitMetrics.xml). It was added on 30 May 2017. This should appear in future runs.
