### ISSUE TITLE
Hydro prep taking a long time

### ISSUE THREAD

**Issue by MattReimer** [SouthForkResearch/CHaMP_Metrics#56]
Hydro prep can currently take up to 30 minutes!

It's such a simple script that we should really investigate ways to reduce that time. 

Not critical but definitely a fun little activity that could really help out our big runs.

**Comment by MattReimer** [comment]
We've combined hydro prep into hydro and so now it takes a miniscule amount of time next to hydro itself. I'm closing this

**Comment by mtnahorniak** [comment]
Question on this - will hydro prep still get done for all VisitIDs?  I.e. if I need to run hydro using my "manual" process (for example to run porous structure runs), will hydro prep still be run, and/or will I still be able to run hydro prep through the workbench if necessary?

**Comment by MattReimer** [comment]
Hydro is being run AND uploaded to both the API and S3 but only as a step inside the delft3D runner. 

If you want to run just hydro prep you can do it manually with the [hydro prep](https://github.com/SouthForkResearch/CHaMP_Metrics/blob/master/tools/hydroprep.py) python script or you can kick off a hydro run and wait for it to upload the hydro prep back to the API and S3.
