### ISSUE TITLE
residual pool depth cv

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#6]
Coefficient of Variation of pool residual depths.

**Comment by philipbaileynar** [comment]
What should the value be if there are zero residual pools? Should it be zero or NULL?

**Comment by volkcj** [comment]
NULL.  No pools means the residual pool depth and rpd CV should be null.

**Comment by philipbaileynar** [comment]
OK @volkcj  then this will remain on hold until Sitka implements the ability to send NULL metrics via the API.

**Comment by philipbaileynar** [comment]
Stale issue. Closing
