### ISSUE TITLE
OGR failing on VISIT_859 shapefile

### ISSUE THREAD

**Issue by MattReimer** [SouthForkResearch/CHaMP_Metrics#61]
Visit 859

From @KellyMWhitehead :

> I cannot for the life of me figure out why this shapefile is having problems loading features using the 'shapefile_loader.py" in champ metrics.
> 
> It keeps bombing out on line 4380 of ogr.py when it trys to convert the geometry to json.
> 
> On the surface, it looks just like a normal breaklines shapefile (x,y,z). This was taken from a Bridge Creek visit, of which all surveys from 2012-2013 appear to be affected. It could that non-standard workflow/equipment could have produced data in a slightly different format, but it seems very odd that this kind of effect would carry over from gdb to shapefile.
> 
> Anyway, if you are able, could you please try loading this and let me know if you are getting the same type of error?

**Comment by MattReimer** [comment]
When OGR loads this shapefile here is what it sees for the first feature:

```
{
  "geometry": {
    "type": "Unknown",
    "coordinates": null
  },
  "type": "Feature",
  "properties": {
    "Shape_Leng": 21.9605148484,
    "TARGET_FID": 0,
    "DESCRIPTIO": "lw",
    "LineType": "SOFT",
    "Join_Count": 19
  },
  "id": 0
}
```

When I load it in GIS I see the type is set to `Line (WKB type: "LineStringZM")` and I wonder if this could be related

**Comment by MattReimer** [comment]
More investigation:

OGR's `GetGeomType()` shows me `3002` --> `ogr.wkbLineStringZM` so that looks fine

it's `feat.ExportToJson()` that shows me `"type": "unknown"`. Very weird

**Comment by MattReimer** [comment]
Followup:

I filed a bug at OSGEO

It's my first one so we'll see how that goes:

### <https://trac.osgeo.org/gdal/ticket/6935>

**Comment by MattReimer** [comment]
More followup:

https://trac.osgeo.org/gdal/changeset/39216

It's been fixed as of Jun 20, 2017 1:43:20 PM

but we won't be able to consume the fix since I refuse to recompile a new version of `trunk` gdal on any of our systems.

**Comment by KellyMWhitehead** [comment]
@MattReimer  Please verify the code updates here: https://gist.github.com/KellyMWhitehead/e4369d9a72b2c6287a8ed78397ff117e

Two issues: 1) Breaklines were still causing an error when trying to load geom as json (so unable to even test if type was unknown in your fix). 2) line 104, I was having issues with some features that did not have a geometry (rare situation). Any advice on when to use 'None' types in theses situations would be appreciated.

Its very crude, but seems to work for me. Feel free to change or improve.

**Comment by MattReimer** [comment]
@KellyMWhitehead Ok. I think it's better to do this than to hack it up like I did. Feel free to make the change and don't just comment out my code. Really get rid of it!

**Comment by MattReimer** [comment]
Hey @KellyMWhitehead I put in some try/catching blocks so that validation can close. Can you just quickly eyeball a2de2ed and make sure I didn't make a mess?
