### ISSUE TITLE
allow alpha numeric characters in Site Properties export Point_Number

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#62]
` "[execPython] Python: [error] [DataException] Control points ShapeFile for Visit ID 566 contains non-numeric point number 'bm202' [0.42]s", '

Reference previous discussion: PB and KW gchat on april 29, 3:44pm`

**Comment by KellyMWhitehead** [comment]
It looks like the point numbers are getting converted to string, but code is checking for non-numeric values and throwing an error: https://github.com/SouthForkResearch/CHaMP_Metrics/blob/master/tools/siteprops.py#L176

**Comment by KellyMWhitehead** [comment]
Desired Output:  PointNum field as string which concatenates values from potential fields ['Point_Numb', 'POINT_NUMB', 'PointNumb', 'POINT_NUM', 'POINT'].

Any string value in this field is fine. No need to check the output values.

**Comment by volkcj** [comment]
fyi--there are 269 failures in site properties right now, and about 250 of these are from this issue.  the remaining 20 errors are missing data or potential orthogonality /transformation issues (survey extents don't overlap).

**Comment by MattReimer** [comment]
@volkcj I'm re-running this in production now. I'll make the logs available.

[HERE](https://drive.google.com/drive/folders/0B_S5WySBF3cBMGpsMXBoMl95dEU) 

(you may want to bookmark this one)
