### ISSUE TITLE
Topo survey CAD file export as AWS engine

### ISSUE THREAD

**Issue by philipbaileynar** [SouthForkResearch/CHaMP_Metrics#63]
We need an AWS engine that can perform the CAD file export that was developed for BPA by @KellyMWhitehead. This produces CSVs and DXF files from a subset of the topo survey layers. Much of the logic can be re-purposed from Kelly's original ESRI-based script. The new engine will be written in Python using Shapely and GDAL.

The goal is to automate the production of the CAD export and upload the output zip file back to visits on cm.org. From there, BPA can retrieve the files via:

1. Workbench (once we get file download working)
1. cm.org on visit tab
1. Custom request to Sitka or SFR

**Comment by KellyMWhitehead** [comment]
Reference: https://gis.stackexchange.com/questions/20734/python-how-to-export-shapely-objects-to-dxf-file
