### ISSUE TITLE
All Tools: No Maude ZIP file found

### ISSUE THREAD

**Issue by MattReimer** [SouthForkResearch/CHaMP_Metrics#73]
I created a sheet showing all the times we tried to find Maude data and failed

<https://docs.google.com/spreadsheets/d/1b21KAWH_qwkuvo7itDXhbAaD4jIGqzKp7Ae-GFMxvuY/edit#gid=1921767537>

Not sure if this is useful or if there's a list you want to check against but here it is.

**Comment by philipbaileynar** [comment]
Closing because this list of visits is out of date.
