### ISSUE TITLE
Aux: LWVol_BfSlow and  and LWVol_WetSlow are the same value

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#77]
I believe LWVol_BfFstTurb is the incorrect value.

To check this, `LWVol_Bf = LWVol_BfFstNT + LWVol_BfSlow + LWVol_BfFstTurb` and this is not currently true.

**Comment by MattReimer** [comment]
This is REALLY hard to debug because of how nesty the code Chris gave us is

I suspect it has something to do with this:

https://github.com/SouthForkResearch/CHaMP_Metrics/blob/master/tools/auxmetrics/metriclib/woodMetrics.py#L154-L169

**Comment by MattReimer** [comment]
@philipbaileynar please update the workbench DB to reflect these changes:

### b481d82
