### ISSUE TITLE
Bf_Vol and Wet_Vol reporting the same value

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#79]
Bf_Vol is reporting the incorrect value.

**Comment by MattReimer** [comment]
![screen shot 2017-10-16 at 10 54 53 am](https://user-images.githubusercontent.com/1063391/31626979-7b73ac36-b260-11e7-9112-8aebc13f2808.png)

**Comment by philipbaileynar** [comment]
The problem is that there is no bankfull wetted surface. When the code attempts to sum all depth raster values within the bankfull extent (blue polygon in Matt's image) there are only values within the wetted extent.

We need a different strategy if we want bankfull volume.

**Comment by philipbaileynar** [comment]
It's agreed that this metric is not properly implemented currently. Retain the metric but set all values to Null in the code until a proper implementation can be done.

**Comment by MattReimer** [comment]
set bankfull one to `None`

**Comment by MattReimer** [comment]
@philipbaileynar could you just check to make sure I set the right thing to None?

![screen shot 2017-10-17 at 9 22 51 am](https://user-images.githubusercontent.com/1063391/31676565-e35707c8-b31c-11e7-97ed-5faa01ffe3d1.png)

**Comment by philipbaileynar** [comment]
This looks good. FYI this is metric ID 45.
