### ISSUE TITLE
Average max pool depth

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#8]
Average max pool depth for a visit.

**Comment by philipbaileynar** [comment]
I actually ended up implementing two new metrics at both the tier 1 and tier 2 channel unit level.

`MaxMaxDepth` is the maximum depth of all channel units of a specific type. It is reported at both the tier 1 and tier 2 type.

`AvgMaxDepth` is the average of the maximum channel unit depths of a specific type. It is also reported at both the tier 1 and tier 2 type.

The **average max pool depth** that this ticket originally requested can be obtained using the XPath:

`/TopoMetrics/Metrics/ChannelUnitsTier1/SlowPool/AvgMaxDepth`

**Comment by philipbaileynar** [comment]
Added to both Workbench and CHaMP Automation metric schema XML on 18 May 2017.
