### ISSUE TITLE
Add BfWMxDRat_Avg And SmSC_Area to default 'Active' list of workbench db

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#82]
This is minor since it can be toggled by users.

**Comment by philipbaileynar** [comment]
1. `BfWMaxDRat_Avg` is already set to Active in version 47 of the workbench database.
1. I cannot find any reference to a metric called `SmSC_Area` in the Workbench.

**Comment by philipbaileynar** [comment]
The `BfWMxDRat_Avg` metric is listed as Active and has an XPath but does not appear in the metric XML definition. This will require a metric definition update for this metric to become visible.

**Comment by philipbaileynar** [comment]
The metric `SmSC_Area` didn't actually exist in the Workbench definitions... but metric ID 3375 appeared to be a legacy version of this metric so it was renamed for this purpose.
