### ISSUE TITLE
PoolResidDpth is 0 when should be null

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#85]
If SlowWater_Ct = 0, PoolResidDepth is null.

see VisitID 1597 is an example with SlowWater_Ct=0 and currently has PoolResidDepth=0.

**Comment by philipbaileynar** [comment]
Resolved. I think this was fixed with another issue relating to null residual depths when there are no channel units of a particular type.

**Comment by volkcj** [comment]
resolved
