### ISSUE TITLE
Topo Channel Metrics do not display in workbench

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#88]
Selecting QA - Topo Channel Metrics in the Metric Review form actually throws a handled exception "A specific cast is not valid".  Listing it here since I'm not sure if it's a workbench bug or missing metric bug.

This same error happens with TopoAux Tier 1 Metrics and Aux Channel Unit schemas.

**Comment by philipbaileynar** [comment]
@volkcj I just released an update to the Workbench (7.0.21) that handles null values in metric schemas. Please download, test and then close this issue if it prevents the error.

**Comment by volkcj** [comment]
Tested and these worth.
