### ISSUE TITLE
Average pool tail crest depth

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#9]
visit level average of pool tail crest depth

**Comment by philipbaileynar** [comment]
This requires the `DepthAtThalwegExit` to be reported for Tier1 `SlowPool`. On 17 May 2017 we started reporting `ResidualDepth` at the tier 1 level but not `DepthAtThalwegExit`.

**Comment by philipbaileynar** [comment]
`DepthAtThalwegExit` is now reported at both the tier 1 and tier 2 level. It is the average value for all channel units through which the Thalweg passes.

The Average Pool Tail Crest Depth metric can be obtained using the `DepthAtThalwegExit` value for tier 1 `Slow Pool` channel units:

`/TopoMetrics/Metrics/ChannelUnitsTier1/SlowPool/DepthAtThalwegExit`

**Comment by philipbaileynar** [comment]
Added to Workbench database and CHaMP Automation metric schema definition on 18 May 2017.
