### ISSUE TITLE
Topo Aux metrics of SC_Area and SC_Area_Pct are NULL in QA schema 

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#90]
Two more null metrics for Visit-level, TopoAux schema.  Visit IDs 3999 and 3997 are examples of IDs that should have these values (Methow 2016 Visits).

**Comment by philipbaileynar** [comment]
@MattReimer can you look at this please. I think it's the class hierarchy that you implemented is not returning the proper dictionary all the way vack to `topoautmetrics.py`. I debugged visit 3999 and I can see the correct values getting calculated in `sidechannel.py`, but the values aren't making it back to the main routine.

**Comment by MattReimer** [comment]
The issue was that we were returning a JSON object, which was the old way of doing things. We nede to remember to set `self.metrics` isntead

This issue also unblocks `LargeWood` calculations that were previously not showing up across the board.

**Comment by volkcj** [comment]
These metrics are no longer null.
