### ISSUE TITLE
LWCount for Aux-ChannelUnit schema is null for 2011-2013 

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#91]
This is likely an incorrect sourcing issue.  The LWD measurement data for 2011-2013 are stored in the LargeWoodyDebris table of cm.org, not the LWDPiece table.  This is because the protocol changed from a categorical size class count to measurement of individual pieces.

**Comment by philipbaileynar** [comment]
Need a Visit ID please. I see the Null values, but I need a concrete example of a visit where there should be a value.

**Comment by volkcj** [comment]
Try Visit ID 542

**Comment by volkcj** [comment]
not resolved.
