### ISSUE TITLE
Inconsistent Nulls between TopoAux and Tier1 metrics

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#95]
This isn't completely diagnosed, but something isn't right and this is a placeholder until I learn more.

Visit 1 has TopoAux-Visit metrics (e.g. SubEstBldr, SubEstCbl, SubEstGrvl) but Visit 1 doesn't have TopoTier1 metrics (e.g. Area, Ct, Freq).   

Possible issues:
-TopoAux metric calc issue
-Tier 1 calc issue
-missing data in combo with one of the above issues.

**Comment by philipbaileynar** [comment]
I actually think that this is perhaps Workbench metric download issue that has been resolved. Please re-test this after a full re-run.

**Comment by volkcj** [comment]
validated with visit 1.
